name: uptime-check

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check sites
        run: |
          check() {
            URL=$1
            STATUS=$(curl -L -o /dev/null -s -w "%{http_code}" $URL)
            TIME=$(date -u +"%Y-%m-%d %H:%M:%S")
            echo "{\"url\":\"$URL\",\"status\":\"$STATUS\",\"time\":\"$TIME\"}"
          }

          echo "[" > status.json
          check "https://dj-matz.nl" >> status.json
          echo "," >> status.json
          check "https://nawijn.nl.eu.org" >> status.json
          echo "," >> status.json
          check "https://vishandelnawijn.nl" >> status.json
          echo "]" >> status.json

      - name: Commit result
        run: |
          git config user.name "bot"
          git config user.email "bot@example.com"
          git add status.json
          git commit -m "update status" || exit 0
          git push
